# reference:
#  - https://aws.amazon.com/graphql/guide11111211/
#  - https://github.com/youyo/aws-cdk-github-actions
name: CDK Diff
on:
  push:
    branches-ignore:
      - main

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCESS_KEY_ID }}:role/TurnipReactInfraStack-LogicGithubActionRole4C78B53C-aDy2hpNoxWlY
          aws-region: us-west-2

      - name: cdk diff
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'diff'
          actions_comment: true
        env:
          AWS_DEFAULT_REGION: 'us-west-2'